source 'http://rubygems.org'

gem 'rails', '2.3.5'
gem 'warden', '0.10.7'
gem 'devise', '1.0.11'
gem 'will_paginate', '2.3.16'
gem 'json', '1.5.0'
gem 'settingslogic'
gem 'fastercsv'
gem 'rest-client','1.6.7'
gem 'mechanize', '1.0.0'
gem 'mysql2'
gem 'mysql'
gem 'activerecord-mysql2-adapter','0.0.3'
gem 'paginate'
gem 'savon'
gem 'mime-types', '1.16'
gem 'nokogiri', '1.5.0'
gem 'passenger'
gem 'hoe','1.8.3'
