## Credentials for PreLink Web Service.
---
wsdl_url: 'http://localhost:3008/prelink_stub/wsdl'
wsdl_namspace: 'http://www.prelink.co.za/'
station_id: '21232f297a57a5a743894a0e4a801fc3'
pass_code: '098f6bcd4621d373cade4e832627b4f6'
