--- 
user: root
group: root
cwd: /var/www/spine_lims/
log_file: /var/www/spine_lims/log/mongrel.log
port: 8000
environment: production
address: 127.0.0.1
pid_file:  /var/www/spine_lims/tmp/pids/mongrel.pid
servers: 3
